<?php
/* Glory to Ukraine! Glory to the heros! */

/** @var Magento\Framework\View\Element\Template $block */

/** @var Codelegacy\RegistryAlternative\ViewModel\BackToCategoryViewModel $viewModel */
$viewModel = $block->getData('backToCategoryVieModel');
$viewModel->getCategoryUrl();

if (!$viewModel->getCategoryUrl()) {
    return ;
}
?>

<div class="back-to-category">
    <a href="<?php echo $viewModel->getCategoryUrl() ?>">
    	<?php echo __(sprintf("Back to %s", $viewModel->getCategoryName())) ?>
    </a>
</div>
