<?php
/* Glory to Ukraine! Glory to the heros! */
/** @var \Codelegacy\SuccessAccess\Block\Adminhtml\System\Config\CreateNewKey $block */
?>
<script>
require([
    'jquery',
    'prototype',
], function($){
    jQuery('#refresh-success-page-debug-seckey').click(function () {
        var params = {
            form_key: '<?php echo $block->getFormKey() ?>',
            isAjax: true
        };

        $.ajax({
            showLoader: true,
            url: "<?php echo $block->getAjaxUrl() ?>",
            data: params,
            dataType: 'json'
        }).done(function (data) {
            window.location.reload();
        });
    });
});
</script>

<?php if ($block->getSecureKey()): ?>
    <p><?= __('Current secure key: <span id="success-page-debug-key"><strong>%1</strong></span>', $block->getSecureKey()) ?></p>
    <p><?= __('Above key must be included as a query parameter to checkout success url eg:') ?></p>
    <p><?= $block->getBaseUrl() . 'checkout/onepage/success/key/' . $block->getSecureKey() . '/order/2000000197' ?></p>
<?php else: ?>
    <p><?= __('Click the button below to generate the required secure key.') ?></p>
<?php endif; ?>


<?= $block->getButtonHtml() ?>
